Адаптер для казахского
morpher-ru/Morpher.WebService.V3.Client pull request #12
Opened 2018-06-08 06:09 UTC by MastAKK

Добавлена казахская версия сервиса WS3

2018-06-09 00:24 UTC, bzaar requested changes

2018-06-09 00:24 UTC, bzaar commented on Morpher.WebService.V3.Client.Samples/Program.cs
> +            var morpherClient = new MorpherClient(); // оба параметра необязательные
Токен нужен, без него не работает демо функций пользовательского словаря.

2018-06-09 00:24 UTC, bzaar commented on Morpher.WebService.V3.Client.Samples/Program.cs
> -            Russian.DeclensionResult declensionResult = russian.Parse("Соединенное королевство");
Не думаю, что "Девять" выдаст приличный результат.

2018-06-09 06:34 UTC, MastAKK commented on Morpher.WebService.V3.Client.Samples/Program.cs
> +            var morpherClient = new MorpherClient(); // оба параметра необязательные
Я про это писал в скайпе с просьбой нового тестового токена (с этим что-то не так), ты тогда сказал, что можно просто убрать token и url.

2018-06-09 06:34 UTC, MastAKK commented on Morpher.WebService.V3.Client.Samples/Program.cs
> -            Russian.DeclensionResult declensionResult = russian.Parse("Соединенное королевство");
Ох, да, извиняюсь, я тестировал возможные ошибки и забыл вернуть на исходную

2018-06-09 14:52 UTC, bzaar commented
К добавлению казахского это изменение не имеет отношения. Давай это
отдельно обсудим. Заведи пожалуйста issue: "Не работает демо-токен".

On Sat, 9 Jun 2018, 08:34 David, <notifications@github.com> wrote:

> *@MastAKK* commented on this pull request.
> ------------------------------
>
> In Morpher.WebService.V3.Client.Samples/Program.cs
> <https://github.com/morpher-ru/Morpher.WebService.V3.Client/pull/12#discussion_r194216716>
> :
>
> > @@ -19,7 +19,7 @@ static void Main()
>              // Зарегистрируйтесь и получите свой token: http://morpher.ru/Register.aspx
>              Guid token = new Guid("a8dab5fe-7a47-4c17-84ea-46facb7d19fe");
>
> -            var morpherClient = new MorpherClient(token, url); // оба параметра необязательные
> +            var morpherClient = new MorpherClient(); // оба параметра необязательные
>
> Я про это писал в скайпе с просьбой нового тестового токена (с этим что-то
> не так), ты тогда сказал, что можно просто убрать token и url.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/morpher-ru/Morpher.WebService.V3.Client/pull/12#discussion_r194216716>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AD15-hqbPhf33uPiDh3u7XPLAemWzFfIks5t62xggaJpZM4Ufi3T>
> .
>

2018-11-30 19:29 UTC, my-official commented
PR обновлен

2018-12-19 11:41 UTC, bzaar approved these changes

2018-12-19 11:41 UTC, bzaar commented on Morpher.WebService.V3.Client.Samples/Program.cs
> +            ReadLine();
Не имеет отношения к добавлению казахского.

2018-12-20 16:24 UTC, my-official commented on Morpher.WebService.V3.Client.Samples/Program.cs
> +            ReadLine();
Да, дебаг забыл выпилить

2018-12-20 16:29 UTC, merged

2018-12-20 16:36 UTC, my-official commented on Morpher.WebService.V3.Client.Samples/Program.cs
> +            ReadLine();
Кстати, это и не мой ReadLine и он Outdated