ArgumentNotQazaqException
morpher-ru/Morpher.WebService.V3.Client pull request #14
Opened 2019-03-05 07:22 UTC by my-official

Добавил QazaqWebClient, выбрасывающий ArgumentNotQazaqException. Добавил тест

2019-03-05 20:15 UTC, bzaar requested changes

2019-03-05 20:15 UTC, bzaar commented on Morpher.WebService.V3.Client.UnitTests/Qazaq.cs
> +            webClient.Setup(client => client.DownloadString(It.IsAny<string>())).Throws(new Morpher.WebService.V3.Qazaq.ArgumentNotQazaqException());
Читер ;) DownloadString в реальности никогда не выбросит ArgumentNotQazaqException. Он возвращает HTTP Status, который client должен преобразовать в Exception.

2019-03-07 09:12 UTC, my-official commented on Morpher.WebService.V3.Client.UnitTests/Qazaq.cs
> +            webClient.Setup(client => client.DownloadString(It.IsAny<string>())).Throws(new Morpher.WebService.V3.Qazaq.ArgumentNotQazaqException());
Поправил

2019-03-19 22:20 UTC, bzaar approved these changes

2019-03-20 05:32 UTC, merged