Fix/teamcity
morpher-ru/Morpher.WebService.V3.Client pull request #15
Opened 2019-05-17 10:24 UTC by my-official

2019-05-17 10:27 UTC, my-official commented on Morpher.WebService.V3.Client/Morpher.WebService.V3.Client.csproj
> +    <AssemblyVersion>3.0.0</AssemblyVersion>
Это не опечатка, я где-то здесь же нашел подобное использование. Чтобы не нужно было перекомпилировать использующий это сборку код. Но я считаю, что можно и честно "3.1.0" написать

2019-05-19 15:29 UTC, bzaar requested changes

2019-05-19 15:29 UTC, bzaar commented on Morpher.WebService.V3.Client/Morpher.WebService.V3.Client.nuspec
> +</package>
А зачем нам .nuspec, если пакет можно из .csproj собирать?

2019-05-19 15:29 UTC, bzaar commented on Morpher.WebService.V3.Client/Morpher.WebService.V3.Client.csproj
> +    <AssemblyVersion>3.0.0</AssemblyVersion>
Да, 3.1.0 можно для следующей версии указать, в которой добавился казахский. Правда, не очень понимаю, почему переход на TeamCity влияет на номера версий.

2019-05-19 15:29 UTC, bzaar commented on Morpher.WebService.V3.Client/Morpher.WebService.V3.Client.nuspec
> +</package>
Давай что-нибудь одно, csproj или nuspec. А то и там, и там версии - непонятно, чему верить. Я за .csproj.

2019-05-19 15:31 UTC, bzaar commented on Morpher.WebService.V3.Client/Morpher.WebService.V3.Client.nuspec
> +</package>
https://docs.microsoft.com/en-us/nuget/create-packages/creating-a-package#from-a-visual-studio-project

2019-07-10 16:51 UTC, closed without merging