Исправление экранирования символа плюс.
morpher-ru/Morpher.WebService.V3.Client pull request #18
Opened 2019-07-11 06:47 UTC by my-official

2019-07-19 12:11 UTC, bzaar requested changes

2019-07-19 12:11 UTC, bzaar commented on Morpher.WebService.V3.Client/MyWebClient.cs
> +            _webClient.QueryString.Add(name, value.Replace("+", "%2B"));
Может быть, лучше использовать HttpUtility.UrlEncode? А то мало ли какие еще там символы неправильно экранируются.

2019-07-23 19:22 UTC, my-official commented on Morpher.WebService.V3.Client/MyWebClient.cs
> +            _webClient.QueryString.Add(name, value.Replace("+", "%2B"));
Заменил на использование Uri.EscapeDataString

2019-07-23 19:29 UTC, my-official commented on Morpher.WebService.V3.Client/MyWebClient.cs
> +            _webClient.QueryString.Add(name, value.Replace("+", "%2B"));
Использовать явное экранирование не хотел, так как _webClient сам экранирует. Проблема именно с плюсом. И не у меня одного:
https://stackoverflow.com/questions/8517511/c-sharp-escape-plus-sign-in-post-using-httpwebrequest
Рекомендуют Uri.EscapeDataString. Впрочем, там у них POST-запрос.
Выбрал Uri.EscapeDataString.

2019-07-23 19:42 UTC, my-official commented on Morpher.WebService.V3.Client/MyWebClient.cs
> +            _webClient.QueryString.Add(name, value.Replace("+", "%2B"));
Добавил тест и исправил старые тесты из-за того, что они проверяли значение в этом NameValueCollection, а теперь они всегда уже закодированные

2019-09-24 08:34 UTC, bzaar approved these changes

2019-09-24 09:25 UTC, merged